services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
        USE_CUDA: true
        USE_OLLAMA: false
      dockerfile: Dockerfile.dev
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - ./src:/app/src
      - ./backend:/app/backend
      - ./umc:/app/umc
    ports:
      - 11222:8080
    environment:
      - PORT=8080
      - ENV=dev
      - 'WEBUI_SECRET_KEY='
      - 'WEBUI_NAME=U-AI'
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11435'
      - 'OPENAI_API_BASE_URLS=http://host.docker.internal:10016 ; http://172.29.0.35:9099'
      - 'OPENAI_API_KEYS= sadfjlkwer.msdf ; 0p3n-w3bu!'
    extra_hosts:
      - "host.docker.internal:192.168.1.103"
    restart: unless-stopped
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: all
              capabilities:
                - gpu


volumes:
  ollama: {}
  open-webui: {}
